import dayjs from "dayjs";
import {
  CLOCK_OUT_METHODS,
  CLOCKOUT_METHOD_CLASSES,
} from "./dashboardConstants.js";
import { formatDecimal } from "./math.js";
import { formatID } from "./formatString.js";

export function getAutoGeneratedClockOutDate(clockList) {
  let autoGeneratedClockOutDate = [];
  clockList.forEach((clock) => {
    if (clock.clockoutMethod === CLOCK_OUT_METHODS.AUTO_GENERATED) {
      autoGeneratedClockOutDate.push(
        dayjs(clock.startTime).format("DD/MM/YYYY"),
      );
    }
  });
  return autoGeneratedClockOutDate;
}

export function getClockoutMethodColor(clockoutMethod) {
  return (
    CLOCKOUT_METHOD_CLASSES[clockoutMethod] || CLOCKOUT_METHOD_CLASSES.DEFAULT
  );
}

export function getNoteOfLatestClockIn(clockList, currentClockId) {
  if ((!clockList && clockList.length === 0) || !currentClockId) return "";
  const latestClockIn = clockList.find((clock) => clock.id === currentClockId);
  return latestClockIn ? latestClockIn.note : "";
}

export function formatClockTableRow(clock, getHourDiff) {
  return {
    clockInDate: dayjs(clock.startTime).format("DD/MM/YYYY"),
    clockInTime: dayjs(clock.startTime).format("HH:mm:ss"),
    clockOutTime: clock.endTime
      ? dayjs(clock.endTime).format("HH:mm:ss")
      : "Unfinished",
    totalHours: clock.endTime
      ? `${formatDecimal(getHourDiff(clock.startTime, clock.endTime))}h`
      : "Unfinished",
    branch: clock.branch,
    clockoutMethod: clock.clockoutMethod || "Unfinished",
    note: clock.note || "",
  };
}

export function formatStaffTableRow(staff) {
  return {
    status: staff.isActive,
    loginId: formatID(staff.id),
    name: `${staff.firstName} ${staff.lastName}`,
    payRate: staff.payRateCents
      ? `$${formatDecimal(staff.payRateCents / 100)}/hr`
      : "Not set",
    availability: getAvailabilityDaysText(staff.availability) || "Not set",
  };
}

function getAvailabilityDaysText(availability) {
  if (!availability) return "Not set";
  ///console.log("availability: ", availability);
  const availableDays = [];
  Object.entries(availability).forEach(([day, isAvailable]) => {
    if (isAvailable) {
      availableDays.push(day.charAt(0).toUpperCase() + day.slice(1, 3));
    }
  });
  return availableDays.join(", ");
}
