import { getAutoGeneratedClockOutDate } from "../../lib/dashboardUtils";

export function ClockWarningBanner({ tableClockList }) {
  const autoGeneratedDates = getAutoGeneratedClockOutDate(tableClockList);

  if (autoGeneratedDates.length === 0) {
    return null;
  }

  return (
    <div className="bg-almond-40 h-13 mt-5 flex items-center">
      <span className="ml-15 text-mocha text-sm">
        <b>Warning:</b> Your shifts on {autoGeneratedDates.join(", ")} were
        auto-closed at 17:00. Please contact admin for further adjustments.
      </span>
    </div>
  );
}
